- app/routes.js
- app/views/current/views/confirmation.html
- app/views/current/views/question.html
- app/views/current/views/start.html
- app/views/index.html
- app/views/v1/routes/_routes.js
- app/views/v1/views/guidance-2019.html
- app/views/v1/views/guidance.html
- app/views/v1/views/includes/breadcrumb_examples.html
- app/views/v1/views/includes/cookie-banner.html
- app/views/v1/views/includes/head.html
- app/views/v1/views/includes/header-publisher-links.html
- app/views/v1/views/includes/header-publisher.html
- app/views/v1/views/includes/scripts.html
- app/views/v1/views/index.html
- app/views/v1/views/layout.html
- app/views/v1/views/layout_unbranded.html
- app/views/v1/views/layouts/GUIDANCE.html
- app/views/v1/views/layouts/GUIDANCELINKS.html
- app/views/v1/views/layouts/_BASE.html
- app/views/v1/views/layouts/_BASEFULL.html
Added new folder for large grants
> added new sprint

- app/routes.js
- app/views/current/routes/_routes.js
- app/views/current/views/country-fail.html
- app/views/current/views/country.html
- app/views/current/views/farming-type-fail.html
- app/views/current/views/farming-type.html
- app/views/current/views/index.html
- app/views/current/views/legal-status-fail.html
- app/views/current/views/legal-status.html
- app/views/current/views/project-cost.html
- app/views/current/views/start.html
- app/views/current/views/tenancy-length-fail.html
- app/views/current/views/tenancy-length.html
- app/views/current/views/tenancy.html
> added eligibility questions

- app/routes.js
- app/views/current/views/applicant-details.html
- app/views/current/views/check-answers-contact-details.html
- app/views/current/views/your-details.html
Setting the back link URL via routes depending on answers to contact questions
> Back links for contact pages

- app/views/current/routes/_routes.js
- app/views/current/views/water/business.html
- app/views/current/views/water/farming-type.html
- app/views/current/views/water/project-items.html
- app/views/current/views/water/task-list.html
Added missing content to task list page.
Started on the back links for the CYA page in section 1
> V3 task list

- app/routes.js
- app/views/current/routes/_routes-slurry.js
- app/views/current/routes/_routes.js
- app/views/current/views/slurry/task-list.html
Fixed a few things so task list now working for slurry.
> Slurry task list working

- app/views/current/views/water/legal-status.html
New changes for the water-legal-status page
> in water-legal-status page ,added extra radio button

- app/views/current/views/water/irrigation-water-source.html
added a new checkbox for the first question and removed a checkbox for the second question
> water-irrigation-source added new checkbox

- app/views/water/v1/views/guidance.html
> Test commit

- app/views/robotics/current/answers.html
- app/views/robotics/current/associated-works.html
- app/views/robotics/current/business.html
- app/views/robotics/current/energy-source.html
- app/views/robotics/current/project-purchase.html
- app/views/robotics/current/project-start.html
- app/views/robotics/current/remaining-costs.html
- app/views/robotics/current/routes/routes.js
- app/views/robotics/index.html
- app/views/slurry/current/answers.html
- app/views/slurry/current/business.html
- app/views/slurry/current/project-start.html
- app/views/slurry/current/remaining-costs.html
All changes goes into v1 from FFTF-1566 except pt.28.
> UR changes

- app/views/robotics/current/agricultural-sector.html
- app/views/robotics/current/answers.html
- app/views/robotics/current/farming-type.html
- app/views/robotics/current/guidance.html
- app/views/robotics/current/other-robotic-conditional2.html
- app/views/robotics/current/other-robotic-fail2.html
- app/views/robotics/current/start.html
- app/views/slurry/current/farming-type.html
- app/views/slurry/current/guidance.html
- app/views/slurry/current/start.html
Changes applied based on ticket [FFTF-1628](https://eaflood.atlassian.net/browse/FFTF-1628?atlOrigin=eyJpIjoiYTg5N2YzMGRhN2U3NDYzOGEzZDBmMjBhNGFjZGE3MDMiLCJwIjoiaiJ9)
> Robotics Round 3 changes

- app/views/index.html
- app/views/robotics/current/business.html
- app/views/robotics/current/check-details.html
- app/views/robotics/current/consent.html
- app/views/robotics/current/farmer-details.html
- app/views/robotics/current/guidance.html
- app/views/robotics/current/other-robotic-equipment.html
- app/views/robotics/current/project-cost.html
- app/views/robotics/current/project-start.html
- app/views/robotics/current/reference-number.html
- app/views/robotics/index.html
- app/views/slurry/current/business.html
- app/views/slurry/current/check-details.html
- app/views/slurry/current/consent.html
- app/views/slurry/current/farmer-details.html
- app/views/slurry/current/guidance.html
- app/views/slurry/current/project-start.html
- app/views/slurry/current/reference-number.html
Changes done based on [[FFTF-1644](https://eaflood.atlassian.net/wiki/spaces/FG/pages/3453943931/Robotics+Design+Content+Changes+Actions)]
> Robotics and Slurry changes

- app/views/index.html
- app/views/robotics/current/grant.html
- app/views/robotics/current/guidance2.html
- app/views/robotics/current/remaining-costs.html
- app/views/robotics/current/routes/routes.js
- app/views/robotics/current/views/layouts/GUIDANCEROBOTICS2.html
- app/views/robotics/index.html
- app/views/slurry/current/grant.html
- app/views/slurry/current/guidance2.html
- app/views/slurry/current/remaining-costs.html
- app/views/slurry/current/views/layouts/GUIDANCESLURRY2.html
- app/views/slurry/index.html
Fixes and changes based on [FFTF-1709](https://eaflood.atlassian.net/browse/FFTF-1709)
> project cost fix and guidance v2

- app/views/addingvalue/current/guidance.html
- app/views/addingvalue/current/guidance2.html
- app/views/addingvalue/current/tenancy.html
- app/views/index.html
- app/views/robotics/current/guidance.html
- app/views/robotics/current/guidance2.html
- app/views/robotics/current/introducing-innovation.html
- app/views/robotics/current/tenancy.html
- app/views/robotics/current/wider-farming.html
- app/views/robotics/index.html
- app/views/slurry/current/guidance.html
- app/views/slurry/current/guidance2.html
- app/views/slurry/current/tenancy.html
- app/views/slurry/index.html
> content fixes

- app/views/addingvalue/current/adding-value.html
- app/views/addingvalue/current/current-customers.html
- app/views/addingvalue/current/future-customers.html
- app/views/addingvalue/current/guidance.html
- app/views/addingvalue/current/project-impact.html
- app/views/addingvalue/current/start.html
- app/views/addingvalue/current/tenancy.html
> Iterations R2

- app/views/addingvalue/current/views/layouts/GUIDANCEADDINGVALUE.html
> Guidance update

- app/views/addingvalue/current/guidance.html
- app/views/addingvalue/current/project-items.html
- app/views/addingvalue/current/where-products-sold.html
- app/views/addingvalue/index.html
- app/views/index.html
Issues 19 to 30 from Confluence document.
https://eaflood.atlassian.net/wiki/spaces/FG/pages/3630694446/Adding+Value+Design+Content+Changes+Actions
> 2nd round of iterations - on AV

- app/views/robotics/current/guidance.html
- app/views/robotics/current/start.html
- app/views/slurry/current/guidance.html
- app/views/slurry/current/start.html
Latest guidance and start pages updated on both Robotics/Slurry.
> guidance and start page changes

- package-lock.json
- package.json
fix: package.json & package-lock.json to reduce vulnerabilities
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908
[snyk-fix-677e55f52684b39ebe8e78aa48362d15](https://github.com/DEFRA/grants-prototype/compare/snyk-fix-677e55f52684b39ebe8e78aa48362d15) ([#188](https://github.com/DEFRA/grants-prototype/pull/188))
> snyk-fix-677e55f52684b39ebe8e78aa48362d15

- app/views/addingvalue/current/business-type-fail.html
- app/views/addingvalue/current/business-type.html
- app/views/addingvalue/current/future-customers.html
- app/views/addingvalue/current/routes/routes.js
- app/views/addingvalue/current/tenancy-length.html
- app/views/addingvalue/current/tenancy.html
- app/views/addingvalue/index.html
- app/views/index.html
This version was not tested yet and [includes issues 53 to 59 from Confluence](https://eaflood.atlassian.net/wiki/spaces/FG/pages/3630694446/Adding+Value+Design+Content+Changes+Actions).
> Avchanges2022

- app/views/addingvalue/current/business-type-fail.html
- app/views/addingvalue/current/business-type.html
- app/views/addingvalue/current/planning-permission-fail.html
- app/views/addingvalue/current/planning-permission.html
- app/views/addingvalue/current/planning-required-condition.html
- app/views/addingvalue/current/products-processed.html
This version was not tested yet and [includes issues 62 to 67 from Confluence](https://eaflood.atlassian.net/wiki/spaces/FG/pages/3630694446/Adding+Value+Design+Content+Changes+Actions).
> Changes 62 to 67

- app/views/addingvalue/current/project-cost.html
- app/views/addingvalue/current/project-items.html
- app/views/addingvalue/current/routes/routes.js
- app/views/addingvalue/current/storage.html
- app/views/addingvalue/index.html
- app/views/index.html
This version was not tested yet and <a href='https://eaflood.atlassian.net/wiki/spaces/FG/pages/3630694446/Adding+Value+Design+Content+Changes+Actions' target="new" class="govuk-link--no-visited-state">includes issues 53 to 67 and 72 from Confluence</a>.
> issues 53 to 67 and 72

- app/views/addingvalue/current/adding-value.html
- app/views/addingvalue/current/answers.html
- app/views/addingvalue/current/environmental-impact.html
- app/views/addingvalue/current/grant.html
- app/views/addingvalue/current/guidance.html
- app/views/addingvalue/current/remaining-costs.html
- app/views/addingvalue/index.html
- app/views/index.html
This version was not tested yet and [includes issues 48 to 75 from Confluence](https://eaflood.atlassian.net/wiki/spaces/FG/pages/3630694446/Adding+Value+Design+Content+Changes+Actions).
> Full submit of issues 48 to 75

- app/views/slurrystorage/utils.js
Detailed issues 37 to 42 added from [Confluence](https://eaflood.atlassian.net/wiki/spaces/GRA/pages/3903324471/Slurry+2022+I+Design+Content+Changes+I+Actions)
> Issues 37 to 42

- app/views/robotics/v1/guidance.html
Please enter the commit message for your changes. Lines starting
> question mark added to guidance header for test
